<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<!DOCTYPE html><html lang="pt-BR"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>GW FRETE | Relatório de Veículos</title><link rel="stylesheet" href="${pageContext.request.contextPath}/assets/css/app.css?v=app-20260510-reports-full"><script defer src="${pageContext.request.contextPath}/assets/js/theme.js?v=theme-20260510-ui"></script></head>
<body class="theme-dark"><fmt:setLocale value="pt_BR"/><main class="app-shell"><jsp:include page="/WEB-INF/views/includes/sidebar.jsp"><jsp:param name="ativo" value="relatorios" /></jsp:include><section class="app-content">
<header class="page-header"><div><span class="page-kicker">Relatórios gerenciais</span><h1>Relatório de veículos</h1><p>Frota, capacidade, quilometragem e status operacional dos veículos.</p></div><div class="page-actions"><jsp:include page="/WEB-INF/views/includes/header.jsp" /><a class="button button-secondary" href="${pageContext.request.contextPath}/relatorios">Central de relatórios</a><a class="button button-secondary" href="${pageContext.request.contextPath}/veiculos">Veículos</a></div></header>
<c:if test="${not empty mensagemErro}"><p class="message message-error" role="alert">${mensagemErro}</p></c:if>
<section class="content-card filter-panel"><div class="filter-panel-header"><div><span class="summary-label">Ações</span><h2>Relatório de veículos</h2></div><p>Limpe filtros ou exporte os dados em PDF ou Excel.</p></div><div class="report-filters-actions"><a class="button button-secondary" href="${pageContext.request.contextPath}/relatorios/veiculos">Limpar filtros</a><a class="button button-secondary" href="${pageContext.request.contextPath}/relatorios/veiculos/pdf" target="_blank" rel="noopener">Exportar PDF</a><a class="button button-secondary" href="${pageContext.request.contextPath}/relatorios/veiculos/excel">Exportar Excel</a></div></section>
<section class="summary-grid"><article class="summary-card"><span class="summary-label">Total veículos</span><strong>${totalVeiculos}</strong><small>Frota</small></article><article class="summary-card"><span class="summary-label">Disponíveis</span><strong>${veiculosDisponiveis}</strong><small>Prontos</small></article><article class="summary-card"><span class="summary-label">Em manutenção</span><strong>${veiculosManutencao}</strong><small>Restritos</small></article><article class="summary-card"><span class="summary-label">Inativos</span><strong>${veiculosInativos}</strong><small>Fora de operação</small></article></section>
<section class="content-card"><div class="table-wrap"><table class="data-table report-table"><thead><tr><th>Placa</th><th>Modelo</th><th>Tipo</th><th>Status</th><th>Capacidade</th><th>Quilometragem</th><th>Data criação</th></tr></thead><tbody><c:forEach var="v" items="${veiculos}"><tr><td><strong class="plate-code">${v.placa}</strong></td><td>${v.modelo}</td><td><span class="badge badge-tipo-${v.tipo.name().toLowerCase()}">${v.tipo.descricao}</span></td><td><span class="badge badge-status-${v.status.name().toLowerCase()}">${v.status.descricao}</span></td><td class="text-muted"><fmt:formatNumber value="${v.capacidade}" pattern="#,##0.00"/> kg</td><td class="text-muted"><fmt:formatNumber value="${v.quilometragem}" pattern="#,##0"/> km</td><td class="text-muted"><fmt:formatDate value="${v.dataCriacaoFormatada}" pattern="dd/MM/yyyy HH:mm"/></td></tr></c:forEach><c:if test="${empty veiculos}"><tr><td colspan="7"><div class="empty-state">Nenhum veículo disponível para o relatório.</div></td></tr></c:if></tbody></table></div></section>
</section></main></body></html>
