<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<!DOCTYPE html><html lang="pt-BR"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>GW FRETE | Relatório de Clientes</title><link rel="stylesheet" href="${pageContext.request.contextPath}/assets/css/app.css?v=app-20260510-reports-full"><script defer src="${pageContext.request.contextPath}/assets/js/theme.js?v=theme-20260510-ui"></script></head>
<body class="theme-dark"><main class="app-shell"><jsp:include page="/WEB-INF/views/includes/sidebar.jsp"><jsp:param name="ativo" value="relatorios" /></jsp:include><section class="app-content">
<header class="page-header"><div><span class="page-kicker">Relatórios gerenciais</span><h1>Relatório de clientes</h1><p>Base cadastral de clientes, tipo, localização e status.</p></div><div class="page-actions"><jsp:include page="/WEB-INF/views/includes/header.jsp" /><a class="button button-secondary" href="${pageContext.request.contextPath}/relatorios">Central de relatórios</a><a class="button button-secondary" href="${pageContext.request.contextPath}/clientes">Clientes</a></div></header>
<c:if test="${not empty mensagemErro}"><p class="message message-error" role="alert">${mensagemErro}</p></c:if>
<section class="content-card filter-panel"><div class="filter-panel-header"><div><span class="summary-label">Ações</span><h2>Relatório de clientes</h2></div><p>Gere a visão atual ou exporte os dados em PDF.</p></div><div class="report-filters-actions"><a class="button button-primary" href="${pageContext.request.contextPath}/relatorios/clientes">Gerar relatório</a><a class="button button-secondary" href="${pageContext.request.contextPath}/relatorios/clientes/pdf" target="_blank" rel="noopener">Exportar PDF</a></div></section>
<section class="summary-grid"><article class="summary-card"><span class="summary-label">Total clientes</span><strong>${totalClientes}</strong><small>Cadastros</small></article><article class="summary-card"><span class="summary-label">Pessoas físicas</span><strong>${pessoasFisicas}</strong><small>PF</small></article><article class="summary-card"><span class="summary-label">Pessoas jurídicas</span><strong>${pessoasJuridicas}</strong><small>PJ</small></article><article class="summary-card"><span class="summary-label">Clientes ativos</span><strong>${clientesAtivos}</strong><small>Ativos</small></article></section>
<section class="content-card"><div class="table-wrap"><table class="data-table report-table"><thead><tr><th>Nome</th><th>Tipo</th><th>CPF/CNPJ</th><th>Email</th><th>Telefone</th><th>Cidade</th><th>Estado</th><th>Status</th></tr></thead><tbody><c:forEach var="c" items="${clientes}"><tr><td><strong>${c.nome}</strong></td><td>${c.tipo.descricao}</td><td class="text-muted">${c.cpfCnpj}</td><td class="text-muted">${empty c.email ? '-' : c.email}</td><td class="text-muted">${empty c.telefone ? '-' : c.telefone}</td><td>${empty c.cidade ? '-' : c.cidade}</td><td class="text-muted">${empty c.estado ? '-' : c.estado}</td><td><span class="badge ${c.status ? 'badge-ativo' : 'badge-inativo'}">${c.statusDescricao}</span></td></tr></c:forEach><c:if test="${empty clientes}"><tr><td colspan="8"><div class="empty-state">Nenhum cliente disponível para o relatório.</div></td></tr></c:if></tbody></table></div></section>
</section></main></body></html>
