<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<!DOCTYPE html><html lang="pt-BR"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>GW FRETE | Relatório de Ocorrências</title><link rel="stylesheet" href="${pageContext.request.contextPath}/assets/css/app.css?v=app-20260510-reports-full"><script defer src="${pageContext.request.contextPath}/assets/js/theme.js?v=theme-20260510-ui"></script></head>
<body class="theme-dark"><main class="app-shell"><jsp:include page="/WEB-INF/views/includes/sidebar.jsp"><jsp:param name="ativo" value="relatorios" /></jsp:include><section class="app-content">
<header class="page-header"><div><span class="page-kicker">Relatórios gerenciais</span><h1>Relatório de ocorrências</h1><p>Eventos operacionais, entregas, avarias e extravios registrados nos fretes.</p></div><div class="page-actions"><jsp:include page="/WEB-INF/views/includes/header.jsp" /><a class="button button-secondary" href="${pageContext.request.contextPath}/relatorios">Central de relatórios</a><a class="button button-secondary" href="${pageContext.request.contextPath}/ocorrencias-frete">Ocorrências</a></div></header>
<c:if test="${not empty mensagemErro}"><p class="message message-error" role="alert">${mensagemErro}</p></c:if>
<section class="content-card filter-panel"><div class="filter-panel-header"><div><span class="summary-label">Ações</span><h2>Relatório de ocorrências</h2></div><p>Limpe filtros ou exporte os dados em PDF.</p></div><div class="report-filters-actions"><a class="button button-secondary" href="${pageContext.request.contextPath}/relatorios/ocorrencias">Limpar filtros</a><a class="button button-secondary" href="${pageContext.request.contextPath}/relatorios/ocorrencias/pdf" target="_blank" rel="noopener">Exportar PDF</a></div></section>
<section class="summary-grid"><article class="summary-card"><span class="summary-label">Total ocorrências</span><strong>${totalOcorrencias}</strong><small>Eventos</small></article><article class="summary-card"><span class="summary-label">Entregas realizadas</span><strong>${entregasRealizadas}</strong><small>Concluídas</small></article><article class="summary-card"><span class="summary-label">Avarias</span><strong>${avarias}</strong><small>Registros críticos</small></article><article class="summary-card"><span class="summary-label">Extravios</span><strong>${extravios}</strong><small>Registros críticos</small></article></section>
<section class="content-card"><div class="table-wrap"><table class="data-table report-table"><thead><tr><th>Frete</th><th>Tipo ocorrência</th><th>Data/hora</th><th>Localização</th><th>Descrição</th><th>Recebedor</th></tr></thead><tbody><c:forEach var="o" items="${ocorrencias}"><tr><td><strong class="freight-code">${o.frete}</strong></td><td><span class="badge badge-ocorrencia-${o.tipo.name().toLowerCase()}">${o.tipo.descricao}</span></td><td class="text-muted"><fmt:formatDate value="${o.dataHoraFormatada}" pattern="dd/MM/yyyy HH:mm"/></td><td>${o.localizacao}</td><td class="text-muted">${empty o.descricao ? '-' : o.descricao}</td><td class="text-muted">${empty o.recebedor ? '-' : o.recebedor}</td></tr></c:forEach><c:if test="${empty ocorrencias}"><tr><td colspan="6"><div class="empty-state">Nenhuma ocorrência disponível para o relatório.</div></td></tr></c:if></tbody></table></div></section>
</section></main></body></html>
