<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<!DOCTYPE html>
<html lang="pt-BR">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>GW FRETE | Relatório de Manutenções</title><link rel="stylesheet" href="${pageContext.request.contextPath}/assets/css/app.css?v=app-20260510-reports-full"><script defer src="${pageContext.request.contextPath}/assets/js/theme.js?v=theme-20260510-ui"></script></head>
<body class="theme-dark"><fmt:setLocale value="pt_BR"/><main class="app-shell"><jsp:include page="/WEB-INF/views/includes/sidebar.jsp"><jsp:param name="ativo" value="relatorios" /></jsp:include><section class="app-content">
<header class="page-header"><div><span class="page-kicker">Relatórios gerenciais</span><h1>Relatório de manutenções</h1><p>Custos, oficina, status e agenda de manutenção da frota.</p></div><div class="page-actions"><jsp:include page="/WEB-INF/views/includes/header.jsp" /><a class="button button-secondary" href="${pageContext.request.contextPath}/relatorios">Central de relatórios</a><a class="button button-secondary" href="${pageContext.request.contextPath}/manutencoes">Manutenções</a></div></header>
<c:if test="${not empty mensagemErro}"><p class="message message-error" role="alert">${mensagemErro}</p></c:if>
<section class="content-card filter-panel"><div class="filter-panel-header"><div><span class="summary-label">Ações</span><h2>Relatório de manutenções</h2></div><p>Gere a visão atual ou exporte os dados em PDF.</p></div><div class="report-filters-actions"><a class="button button-primary" href="${pageContext.request.contextPath}/relatorios/manutencoes">Gerar relatório</a><a class="button button-secondary" href="${pageContext.request.contextPath}/relatorios/manutencoes/pdf" target="_blank" rel="noopener">Exportar PDF</a></div></section>
<section class="summary-grid"><article class="summary-card"><span class="summary-label">Total manutenções</span><strong>${totalManutencoes}</strong><small>Registros</small></article><article class="summary-card"><span class="summary-label">Em andamento</span><strong>${manutencoesEmAndamento}</strong><small>Execução atual</small></article><article class="summary-card"><span class="summary-label">Concluídas</span><strong>${manutencoesConcluidas}</strong><small>Finalizadas</small></article><article class="summary-card"><span class="summary-label">Custo total</span><strong><fmt:formatNumber value="${custoTotal}" type="currency"/></strong><small>Valor acumulado</small></article></section>
<section class="content-card"><div class="table-wrap"><table class="data-table report-table"><thead><tr><th>Veículo</th><th>Tipo</th><th>Status</th><th>Descrição</th><th>Oficina</th><th>Custo</th><th>Agendada</th><th>Conclusão</th></tr></thead><tbody><c:forEach var="m" items="${manutencoes}"><tr><td><strong>${m.veiculo}</strong></td><td>${m.tipo.descricao}</td><td><span class="badge badge-manutencao-${m.status.name().toLowerCase()}">${m.status.descricao}</span></td><td class="text-muted">${m.descricao}</td><td class="text-muted">${empty m.oficina ? '-' : m.oficina}</td><td class="text-muted"><fmt:formatNumber value="${m.custo}" type="currency"/></td><td class="text-muted"><fmt:formatDate value="${m.dataAgendadaFormatada}" pattern="dd/MM/yyyy"/></td><td class="text-muted"><c:choose><c:when test="${not empty m.dataConclusaoFormatada}"><fmt:formatDate value="${m.dataConclusaoFormatada}" pattern="dd/MM/yyyy"/></c:when><c:otherwise>-</c:otherwise></c:choose></td></tr></c:forEach><c:if test="${empty manutencoes}"><tr><td colspan="8"><div class="empty-state">Nenhuma manutenção disponível para o relatório.</div></td></tr></c:if></tbody></table></div></section>
</section></main></body></html>
