<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<!DOCTYPE html><html lang="pt-BR"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>GW FRETE | Relatório de Motoristas</title><link rel="stylesheet" href="${pageContext.request.contextPath}/assets/css/app.css?v=app-20260510-reports-full"><script defer src="${pageContext.request.contextPath}/assets/js/theme.js?v=theme-20260510-ui"></script></head>
<body class="theme-dark"><main class="app-shell"><jsp:include page="/WEB-INF/views/includes/sidebar.jsp"><jsp:param name="ativo" value="relatorios" /></jsp:include><section class="app-content">
<header class="page-header"><div><span class="page-kicker">Relatórios gerenciais</span><h1>Relatório de motoristas</h1><p>Motoristas, CNH, vínculo e status operacional.</p></div><div class="page-actions"><jsp:include page="/WEB-INF/views/includes/header.jsp" /><a class="button button-secondary" href="${pageContext.request.contextPath}/relatorios">Central de relatórios</a><a class="button button-secondary" href="${pageContext.request.contextPath}/motoristas">Motoristas</a></div></header>
<c:if test="${not empty mensagemErro}"><p class="message message-error" role="alert">${mensagemErro}</p></c:if>
<section class="content-card filter-panel"><div class="filter-panel-header"><div><span class="summary-label">Ações</span><h2>Relatório de motoristas</h2></div><p>Limpe filtros ou exporte os dados em PDF ou Excel.</p></div><div class="report-filters-actions"><a class="button button-secondary" href="${pageContext.request.contextPath}/relatorios/motoristas">Limpar filtros</a><a class="button button-secondary" href="${pageContext.request.contextPath}/relatorios/motoristas/pdf" target="_blank" rel="noopener">Exportar PDF</a><a class="button button-secondary" href="${pageContext.request.contextPath}/relatorios/motoristas/excel">Exportar Excel</a></div></section>
<section class="summary-grid"><article class="summary-card"><span class="summary-label">Total motoristas</span><strong>${totalMotoristas}</strong><small>Cadastros</small></article><article class="summary-card"><span class="summary-label">Ativos</span><strong>${motoristasAtivos}</strong><small>Disponíveis</small></article><article class="summary-card"><span class="summary-label">Suspensos</span><strong>${motoristasSuspensos}</strong><small>Restritos</small></article><article class="summary-card"><span class="summary-label">CNHs vencidas</span><strong>${cnhsVencidas}</strong><small>Atenção</small></article></section>
<section class="content-card"><div class="table-wrap"><table class="data-table report-table"><thead><tr><th>Nome</th><th>CPF</th><th>Telefone</th><th>CNH</th><th>Categoria</th><th>Validade CNH</th><th>Vínculo</th><th>Status</th></tr></thead><tbody><c:forEach var="m" items="${motoristas}"><tr><td><strong>${m.nome}</strong></td><td class="text-muted">${m.cpf}</td><td class="text-muted">${empty m.telefone ? '-' : m.telefone}</td><td>${m.cnh}</td><td><span class="badge badge-cnh-${m.categoriaCnh.toLowerCase()}">${m.categoriaCnh}</span></td><td class="text-muted"><fmt:formatDate value="${m.validadeCnhFormatada}" pattern="dd/MM/yyyy"/></td><td><span class="badge badge-vinculo-${m.vinculo.name().toLowerCase()}">${m.vinculo.descricao}</span></td><td><span class="badge badge-motorista-${m.status.name().toLowerCase()}">${m.status.descricao}</span></td></tr></c:forEach><c:if test="${empty motoristas}"><tr><td colspan="8"><div class="empty-state">Nenhum motorista disponível para o relatório.</div></td></tr></c:if></tbody></table></div></section>
</section></main></body></html>
